version: "2"
services:
  web:
    container_name: pay_system_service
    build: .
    command: "npm run test"
    volumes:
      - .:/src/
      - /src/node_modules
    ports:
      - "9998:9998"
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=9999
      - REDIS_URL=redis://paySystem
  redis:
    image: redis:5.0.0
    container_name: paySystem
    expose:
      - 6379
